In [108]:
import pandas as pd
import numpy as np

In [109]:
import requests

url= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_base.csv"
response = requests.get(url)

with open("laptop.csv", "wb") as f:
    f.write(response.content)

In [110]:
file_path = "laptop.csv"
df=pd.read_csv(file_path)
df.head(10)

   Acer  4  IPS Panel  2  1  5   35.56  1.6  8  256 1.6.1   978
0  Dell  3    Full HD  1  1  3  39.624  2.0  4  256   2.2   634
1  Dell  3    Full HD  1  1  7  39.624  2.7  8  256   2.2   946
2  Dell  4  IPS Panel  2  1  5  33.782  1.6  8  128  1.22  1244
3    HP  4    Full HD  2  1  7  39.624  1.8  8  256  1.91   837
4  Dell  3    Full HD  1  1  5  39.624  1.6  8  256   2.2  1016
5    HP  3    Full HD  3  1  5  39.624  1.6  8  256   2.1  1117
6  Acer  3  IPS Panel  2  1  5    38.1  1.6  4  256   2.2   866
7  Dell  3    Full HD  1  1  5  39.624  2.5  4  256   2.3   812
8  Acer  3  IPS Panel  3  1  7    38.1  1.8  8  256   2.2  1068
9  Dell  3    Full HD  1  1  7  39.624  1.8  8  256  2.13   975

In [111]:
## Create A Headers List
headers=["Manufacturer", "Category", "Screen", "GPU", "OS", "CPU_core", "Screen_Size_inch", "CPU_frequency", "RAM_GB", "Storage_GB_SSD", "Weight_kg", "Price"]

In [112]:
df.columns = headers
df

,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
1,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
2,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
3,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
4,Dell,3,Full HD,1,1,5,39.624,1.6,8,256,2.2,1016
...,...,...,...,...,...,...,...,...,...,...,...,...
232,Lenovo,4,IPS Panel,2,1,7,35.56,2.6,8,256,1.7,1891
233,Toshiba,3,Full HD,2,1,5,33.782,2.4,8,256,1.2,1950
234,Lenovo,4,IPS Panel,2,1,5,30.48,2.6,8,256,1.36,2236
235,Lenovo,3,Full HD,3,1,5,39.624,2.5,6,256,2.4,883
236,Toshiba,3,Full HD,2,1,5,35.56,2.3,8,256,1.95,1499

In [113]:
## Replace '?' with 'NaN'

df1 = df.replace("?", np.NaN)
df

,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
1,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
2,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
3,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
4,Dell,3,Full HD,1,1,5,39.624,1.6,8,256,2.2,1016
...,...,...,...,...,...,...,...,...,...,...,...,...
232,Lenovo,4,IPS Panel,2,1,7,35.56,2.6,8,256,1.7,1891
233,Toshiba,3,Full HD,2,1,5,33.782,2.4,8,256,1.2,1950
234,Lenovo,4,IPS Panel,2,1,5,30.48,2.6,8,256,1.36,2236
235,Lenovo,3,Full HD,3,1,5,39.624,2.5,6,256,2.4,883
236,Toshiba,3,Full HD,2,1,5,35.56,2.3,8,256,1.95,1499

In [114]:
## Print the data types of the dataframe columns

print(df1.dtypes)

Manufacturer         object
Category              int64
Screen               object
GPU                   int64
OS                    int64
CPU_core              int64
Screen_Size_inch     object
CPU_frequency       float64
RAM_GB                int64
Storage_GB_SSD        int64
Weight_kg            object
Price                 int64
dtype: object

In [115]:
## Print the statistical description of the dataset, including that of 'object' data types

print(df1.describe())

         Category         GPU          OS    CPU_core  CPU_frequency  \
count  237.000000  237.000000  237.000000  237.000000     237.000000
mean     3.202532    2.151899    1.059072    5.632911       2.363291
std      0.776450    0.639556    0.236258    1.243736       0.409271
min      1.000000    1.000000    1.000000    3.000000       1.200000
25%      3.000000    2.000000    1.000000    5.000000       2.000000
50%      3.000000    2.000000    1.000000    5.000000       2.500000
75%      4.000000    3.000000    1.000000    7.000000       2.700000
max      5.000000    3.000000    2.000000    7.000000       2.900000

           RAM_GB  Storage_GB_SSD        Price
count  237.000000      237.000000   237.000000
mean     7.881857      245.738397  1464.388186
std      2.487845       34.832516   574.956374
min      4.000000      128.000000   527.000000
25%      8.000000      256.000000  1068.000000
50%      8.000000      256.000000  1333.000000
75%      8.000000      256.000000  1777.000000
max     16.000000      256.000000  3810.000000

In [116]:
## Print the summary information of the dataset

print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Manufacturer      237 non-null    object
 1   Category          237 non-null    int64
 2   Screen            237 non-null    object
 3   GPU               237 non-null    int64
 4   OS                237 non-null    int64
 5   CPU_core          237 non-null    int64
 6   Screen_Size_inch  233 non-null    object
 7   CPU_frequency     237 non-null    float64
 8   RAM_GB            237 non-null    int64
 9   Storage_GB_SSD    237 non-null    int64
 10  Weight_kg         232 non-null    object
 11  Price             237 non-null    int64
dtypes: float64(1), int64(7), object(4)
memory usage: 22.3+ KB
None

In [117]:
df1.to_csv("updatedLaptopPrices.csv")