In [4]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from beautifulsoup4) (4.15.0)

In [6]:
!pip install --break-system-packages html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
from bs4 import BeautifulSoup
html="<!DOCTYPE html><head><title>Page Title</title></head><body><h3><b id='boldest'>Lebron James</b></h3><p>Salary: $92,000,000</p><h3>Stephen Curry</h3><p>Salary:$85,000,000</p><h3>Kevin Durant</h3><p>Salary:$73,200,000</p></body></html>"
soup=BeautifulSoup(html,"html5lib")

In [4]:
tag_object=soup.title
print(tag_object)

<title>Page Title</title>

In [5]:
tag_object=soup.h3
print(tag_object)

<h3><b id="boldest">Lebron James</b></h3>

#### find_all()

In [8]:
findall=soup.find_all('h3')
print(findall)

[<h3><b id="boldest">Lebron James</b></h3>, <h3>Stephen Curry</h3>, <h3>Kevin Durant</h3>]

### Web Scraping Tables Using Pandas

In [14]:
!pip install --upgrade pandas --break-system-packages

Requirement already satisfied: pandas in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (3.0.2)
Collecting pandas
  Downloading pandas-3.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp311-cp311-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 55.2 kB/s  0:02:26a 0:00:04m eta 0:00:09m
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 3.0.2
    Uninstalling pandas-3.0.2:
      Successfully uninstalled pandas-3.0.2
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [17]:
!pip install lxml packages

Collecting lxml
  Downloading lxml-6.1.1-cp311-cp311-macosx_10_9_universal2.whl.metadata (3.5 kB)
Collecting packages
  Downloading packages-0.1.1-py3-none-any.whl.metadata (731 bytes)
Collecting cached_property<2.0.0,>=1.5.1 (from packages)
  Downloading cached_property-1.5.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting click<8.0,>=7.0 (from packages)
  Downloading click-7.1.2-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting lxml
  Downloading lxml-4.9.4-cp311-cp311-macosx_11_0_universal2.whl.metadata (3.7 kB)
Collecting pymongo<4.0.0,>=3.10.0 (from packages)
  Downloading pymongo-3.13.0-cp311-cp311-macosx_10_9_universal2.whl.metadata (9.8 kB)
Collecting redis<4.0.0,>=3.3.11 (from packages)
  Downloading redis-3.5.3-py2.py3-none-any.whl.metadata (36 kB)
Requirement already satisfied: requests<3.0.0,>=2.22.0 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from packages) (2.33.1)
Collecting requests-cache<0.6.0,>=0.5.2 (from packages)
  Downloading requests_cache-0.5.2-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting tqdm<5.0.0,>=4.40.2 (from packages)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests<3.0.0,>=2.22.0->packages) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests<3.0.0,>=2.22.0->packages) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests<3.0.0,>=2.22.0->packages) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests<3.0.0,>=2.22.0->packages) (2026.2.25)
Downloading packages-0.1.1-py3-none-any.whl (9.7 kB)
Downloading lxml-4.9.4-cp311-cp311-macosx_11_0_universal2.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 45.2 kB/s  0:02:57 49.7 kB/s eta 0:00:05
Downloading cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Downloading pymongo-3.13.0-cp311-cp311-macosx_10_9_universal2.whl (430 kB)
Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
Downloading requests_cache-0.5.2-py2.py3-none-any.whl (22 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: cached_property, tqdm, redis, pymongo, lxml, click, requests-cache, packages
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [packages]━━ 5/8 [click]o]
Successfully installed cached_property-1.5.2 click-7.1.2 lxml-4.9.4 packages-0.1.1 pymongo-3.13.0 redis-3.5.3 requests-cache-0.5.2 tqdm-4.67.3
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd
from urllib.request import Request, urlopen

URL="https://en.wikipedia.org/wiki/List_of_largest_banks"
req = Request(URL, headers={'User-Agent': 'Mozilla/5.0'})  ## This Line Is Very Important, Otherwise It Will Give Errors
tables = pd.read_html(urlopen(req))
df = tables[0]
df=pd.DataFrame(df)
df

,Rank,Bank name,Total assets (December 2025) (US$ billion)
0,1,Industrial and Commercial Bank of China,7585.85
1,2,Agricultural Bank of China,6979.43
2,3,China Construction Bank,6204.37
3,4,Bank of China,5248.22
4,5,JPMorgan Chase,4424.90
...,...,...,...
95,96,SEB Group,339.65
96,97,Raiffeisen Group,337.25
97,98,Banco Bradesco,331.96
98,99,VTB Bank,330.43
99,100,First Abu Dhabi Bank,330.32

### GDP Extractions

In [10]:
import pandas as pd
URL="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"
req = Request(URL, headers={'User-Agent': 'Mozilla/5.0'})
tables=pd.read_html(urlopen(req))
df=tables[2]
df=pd.DataFrame(df)
df

,Country/Territory,IMF (2026)[1],World Bank (2024)[6],United Nations (2024)[7]
0,World,126295331,111326370,100834796
1,United States,32383920,28750956,29298000
2,China[n 1],20851593,18743803,18743802
3,Germany,5452858,4685593,4659929
4,Japan,4379253,4027598,4026211
...,...,...,...,...
217,Palau,377,277 (2023),310
218,Marshall Islands,342,290,281
219,Nauru,196,163,187
220,Montserrat,—N/a,—N/a,81
221,Tuvalu,65,62 (2023),56